spring.application.name=rest-service


#spring.datasource.url=jdbc:mysql://localhost:3306/market-place
spring.datasource.url=jdbc:mysql://localhost:8889/market-place
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true